# server port
server:
  port: 8080

# database
spring:
  datasource-meta:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meta_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: mysql

  datasource-data:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: mysql

    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: update

# ?? ?? ?? ??
# ??? ??? 1?? ?? ??? ?? ????? ???? ???? ?? ??? ??
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
